export enum Speciality {
    GENERAL = "GENERAL",
    DENTISTE = "DENTISTE",
    CARDIOLOGUE = "CARDIOLOGUE",
    DERMATOLOGUE = "DERMATOLOGUE",
    GYNECOLOGUE = "GYNECOLOGUE",
    OPHTALMOLOGUE = "OPHTALMOLOGUE",
    PEDIATRE = "PEDIATRE",
    PSYCHIATRE = "PSYCHIATRE",
    ORL = "ORL",
    RHUMATOLOGUE = "RHUMATOLOGUE",
    AUTRE = "AUTRE"
}
